In [1]:
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from scipy import stats
from matplotlib import cm

plt.rc('font', family='Malgun Gothic')
plt.style.use('ggplot')
plt.rcParams['axes.facecolor'] = '#f5f5f5'
warnings.filterwarnings('ignore')

colors = ['#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#808080', '#ffffff', '#000000']

In [8]:
df = pd.read_csv("부동산_202211.csv", encoding="cp949")
df.loc[df["전용면적(㎡)"] <= 60, "규모"] = "소형"
df.loc[(df["전용면적(㎡)"] > 60) & (df["전용면적(㎡)"] <= 85), "규모"] = "중형"
df.loc[(df["전용면적(㎡)"] > 85) & (df["전용면적(㎡)"] <= 100), "규모"] = "중대형"
df.loc[df["전용면적(㎡)"] > 100, "규모"] = "대형"
df.head(20)

,시군구,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,규모
0,서울특별시 강남구 개포동,개포래미안포레스트,84.8300,202211,25,"240,000",33,2020,중형
1,서울특별시 강남구 개포동,개포래미안포레스트,84.8600,202211,29,"240,000",5,2020,중형
2,서울특별시 강남구 개포동,디에이치아너힐즈,84.3558,202211,26,"250,000",19,2019,중형
3,서울특별시 강남구 개포동,삼익대청아파트,60.0000,202211,14,"134,000",7,1992,소형
4,서울특별시 강남구 개포동,성원대치2단지아파트,39.5300,202211,15,"102,500",3,1992,소형
5,서울특별시 강남구 개포동,성원대치2단지아파트,33.1800,202211,16,"84,700",13,1992,소형
6,서울특별시 강남구 논현동,로체샤르캐슬,106.5900,202211,10,"139,000",4,2009,대형
7,서울특별시 강남구 논현동,쌍용,84.8700,202211,12,"105,000",3,1996,중형
8,서울특별시 강남구 논현동,한양수자인어반게이트,20.2300,202211,2,"28,000",7,2013,소형
9,서울특별시 강남구 대치동,"대치우성아파트1동,2동,3동,5동,6동,7동",115.5900,202211,22,"260,000",4,1984,대형
10,서울특별시 강남구 대치동,래미안대치팰리스,94.4900,202211,16,"348,000",15,2015,중대형
11,서울특별시 강남구 대치동,래미안대치팰리스,91.9300,202211,17,"291,000",20,2015,중대형
12,서울특별시 강남구 대치동,선경1차(1동-7동),136.6800,202211,11,"385,000",11,1983,대형
13,서울특별시 강남구 대치동,선경3차,76.6000,202211,3,"210,000",7,1990,중형
14,서울특별시 강남구 대치동,은마,84.4300,202211,1,"235,000",10,1979,중형
15,서울특별시 강남구 대치동,은마,76.7900,202211,5,"191,500",10,1979,중형
16,서울특별시 강남구 대치동,은마,76.7900,202211,8,"177,000",1,1979,중형
17,서울특별시 강남구 대치동,은마,84.4300,202211,16,"220,000",4,1979,중형
18,서울특별시 강남구 대치동,은마,84.4300,202211,21,"215,000",5,1979,중형
19,서울특별시 강남구 대치동,은마,84.4300,202211,22,"226,000",12,1979,중형

In [24]:
df["거래금액(만원)"] = df["거래금액(만원)"].replace(',','', regex=True)
df["거래금액(만원)"] = pd.to_numeric(df["거래금액(만원)"])
# df.info()
# sizes = df.groupby(["규모"])["거래금액(만원)"].mean()
# sizes

# 규모별 최빈값
df["규모"].value_counts()

소형     423
중형     239
대형      60
중대형      8
Name: 규모, dtype: int64